### ISSUE TITLE
IOLoop is already running

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Driverless-Competition-Simulator#84]
Get this error while running the operator and clicking 'send GO signal`
```
Exception in thread Thread-41:
Traceback (most recent call last):
  File "C:\Users\sijme\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\sijme\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "webserver.py", line 265, in referee_state_listener
    ref = self.client.getRefereeState()
  File "..\AirSim\PythonClient\airsim\client.py", line 1130, in getRefereeState
    referee_state_raw = self.client.call('getRefereeState')
  File "C:\Users\sijme\AppData\Local\Programs\Python\Python38-32\lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "C:\Users\sijme\AppData\Local\Programs\Python\Python38-32\lib\site-packages\msgpackrpc\future.py", line 25, in get
    self.join()
  File "C:\Users\sijme\AppData\Local\Programs\Python\Python38-32\lib\site-packages\msgpackrpc\future.py", line 22, in join
    self._loop.start()
  File "C:\Users\sijme\AppData\Local\Programs\Python\Python38-32\lib\site-packages\msgpackrpc\loop.py", line 22, in start
    self._ioloop.start()
  File "C:\Users\sijme\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tornado\ioloop.py", line 755, in start
    raise RuntimeError("IOLoop is already running")
```

**Comment by SijmenHuizenga** [comment]
The problem was that the UE game still had a process running on Windows. After going into task manager and killing all unreal engine, FSOnline and Blocks processes the error no longer happend.
